### PR TITLE
feature: added multi language support

### LINKED ISSUE #7: Language Support (Localization)
**Improvement:** Add multi-language support to make the application usable globally, with localization for different languages and time zones.

### PR DESCRIPTION
**Pull request by yazdanhaider**
Feature: Added multiple language support
Fixes #7 
Changes: Added .gitignore

### CODE REVIEW

**Comment by bacloud23** [comment]
Very nice thank you !
please make  translations into a separate JS file; and second, please include only one language that you are proficient in (mother tong)
other GPT generated translations don't look fine to me.

**Comment by bacloud23** [comment]
also what's up with the localization.js file ?!

**Comment by yazdanhaider** [comment]
Separated the translation into localization.js also added only one language (Hindi) which is proficient to me.

Also the localization.js helps to Defines translations, Manages current language, Provides a changeLanguage function, Initializes the language on page load.

**Comment by bacloud23** [comment]
thank you for your contribution ^^

**Pull request merged**
