### PR TITLE
rate limited to 10 sec

### LINKED ISSUE #6: Rate Limiting for Messages
**Issue:** There's no rate limiting for sending messages, so a malicious user could potentially spam the channel with questions or answers.

**Improvement:** Implement rate limiting to prevent spamming by restricting the number of messages a user can send within a certain timeframe.

### PR DESCRIPTION
**Pull request by Mang0codes**
Resolves #6

### CODE REVIEW

**Comment by Mang0codes** [comment]
Screenshot 2024-10-12 012841
The code is working as expected also I added a check where user cannot send empty questions/answers .

**Comment by bacloud23** [comment]
very nice, can you rebase or start again from main.
Can you make it 1 question per 30 seconds please.
Ty :)

**Comment by Mang0codes** [comment]
> very nice, can you rebase or start again from main.

Why rebase? my branch is up-to-date if that's what you mean

**Comment by bacloud23** [comment]
@Mang0codes no not at all x) it is not up to date :)

**Comment by Mang0codes** [comment]
> @Mang0codes no not at all x) it is not up to date :)

Yeah I just realized.. On it!

**Pull request closed without merging**
