### PR TITLE
feat: Improved UI Design

### PR DESCRIPTION
**Pull request by lirena00**
addresses issue #3 

image

### CODE REVIEW

**Comment by lirena00** [comment]
remember to add required labels before merging if u do :)

**Comment by lirena00** [comment]
@bacloud23  😭 atleast add hacktoberfest label on the PR otherwise it wont count as contibution

**Comment by lirena00** [comment]
thanks :) also the new ui better or lol it's worse XD

**Comment by bacloud23** [comment]
I think it is fine no worries. I like the animation.

**Pull request merged**
